name: Maven Compile
on: [push, pull_request]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up OpenJDK 8
              uses: actions/setup-java@v1
              with:
                  java-version: 8.0.232
            - name: Compile with Maven
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: mvn -B compile test -P no-apidoc